# name of your application
export APPLICATION = pHAL_test

# If no BOARD is found in the environment, use this default:
BOARD ?= native
FEATURES_REQUIRED = periph_pwm
USEMODULE += xtimer
USEMODULE += servo
USEMODULE += shell

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../RIOT
include $(RIOTBASE)/Makefile.include




