# name of your application
APPLICATION = pHAL_test

# If no BOARD is found in the environment, use this default:
BOARD ?= native

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../RIOT

USEMODULE += shell
USEMODULE += servo
USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
